version: '3.8'
services:
  nestjs:
    build: .
    ports:
      - "${API_PORT}:3000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      DATABASE_URL: ${DATABASE_URL}
    networks:
      - backend
    command: ["sh", "-c", "npx prisma migrate dev && npm run dev"]

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_USER_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '${DATABASE_PORT}:3306'
    networks:
      - backend

volumes:
  db_data:

networks:
  backend: